config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :admins
  resources :products do
    resource :buy_now, only: [:show, :create], controller: :buy_now do
      get "success", on: :collection
    end
  end

  resources :carts, only: [:create, :show, :destroy] do
    get "checkout", on: :member, to: "carts#checkout"
    post "stripe_session", on: :member, to: "carts#stripe_session"
    get "success", on: :member, to: "carts#success"
  end

  resource :admin, only: [:show], controller: :admin
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/views/layouts/_cart.html.erb
<div class="relative" id="cart">
  <%= image_tag("shopping-cart.png", class: "w-10 object-cover invert") %>
  <% if cart && cart.cart_items.any? %>
    <div class="absolute top-0 -right-3 bg-purple-500 px-1.5 text-sm text-indigo-100 rounded-lg"> 
      <%= cart.cart_items.count %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="h-16 w-full fixed top-0 bg-gray-900 z-50"> 
  <div class="max-w-7xl h-full w-full mx-auto flex items-center justify-between px-8">
    <%= link_to root_path, class: "flex items-end gap-4" do %>
      <%= image_tag("grocery-store.png", class: "w-10 object-cover") %>
      <span class="text-2xl text-gray-100"> E-Commerce Rails </span>
    <% end %>

    <%= link_to cart_path(@current_cart.secret_id) do %>
      <%= render "layouts/cart", cart: @current_cart %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) || "EcommerceRails" %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="stripe-pk" content="<%= Rails.application.credentials.dig(:stripe, :pk) %>">
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body class="bg-gradient-to-r from-indigo-500 via-purple-300 to-indigo-200">
    <%= render "layouts/navbar" %>
    
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>